export const TICKET_POINTS: Record<string, number> = {
  'Corective CSA': 4,
  'Corective MMP': 4,
  'Corective TBG': 4,
  'Corective Power Polaris': 4,
  'Corective Tiwer TIS': 4,
  'Preventive MMP': 2,
  'Preventive CSA': 2,
  'Preventive TBG': 2,
  'Preventive Power Polaris': 2,
  'Preventive Power TIS': 2,
  'Corrective Mitratel': 4,
  'Preventive Fiberisasi': 2,
  'Aktivasi / Migrasi / Dismantel Digiserve': 4,
  'Corrective Digiserve': 4,
  'Relokasi Digiserve': 1,
  'Aktivasi Cross Connect TDE': 4,
  'Corrective Ibu - FTTR': 5,
  'Corrective NuTech': 4,
  'Corrective SNT': 4,
  'Corrective SPBU': 4,
  'Corrective Surge': 4,
  'Inventory SPBU': 4,
  'MS IT & FO SJU': 5,
  'MS Patroli Tellin': 4,
  'Preventive MS SNT': 2,
  'Preventive NuTech': 4,
  'Preventive SPBU': 8,
  'Relokasi DCS': 1,
  'SPPG': 8,
  'Corrective MyRep': 2,
  'Preventive Asianet': 2,
  'HSI Indihome Reseller': 2,
  'Tangible': 4,
  'Tiket Datin Kategory 1': 3,
  'Tiket Datin Kategory 2': 3,
  'Tiket Datin Kategory 3': 3,
  'Tiket HSI Indibiz': 2,
  'Tiket Node B CNQ (Preventive/Quality)': 4,
  'Tiket Node B Critical': 6,
  'Tiket Node B Low': 4,
  'Tiket Node B Minor': 4,
  'Tiket Node B Major': 4,
  'Tiket Node B Premium': 6,
  'Tiket Node B Premium Preventive': 4,
  'Tiket OLO Datin Gamas': 4,
  'Tiket OLO Datin Non Gamas': 4,
  'Tiket OLO Datin Quality': 4,
  'Tiket OLO SL WDM': 4,
  'Tiket OLO SL WDM Quality': 4,
  'Tiket Pra SQM Gaul HSI': 2,
  'Tiket SIP Trunk': 3,
  'Tiket SQM Datin': 3,
  'Tiket SQM HSI': 2,
  'Tiket Wifi Id': 3,
  'Tiket Wifi Logic': 3,
  'Unspec Datin': 3,
  'Unspec HSI': 2,
  'Unspec Site': 4,
  'Unspec Wifi': 2,
  'Validasi Data Ebis': 2,
  'Validasi Data Wifi': 2,
  'Validasi Sewa Tiang': 0.25,
};
